-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userName` VARCHAR(191) NOT NULL,
    `salt` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` DATETIME(3) NULL,

    UNIQUE INDEX `User_userName_key`(`userName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Template` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NULL,
    `details` TEXT NULL,
    `userId` INTEGER NOT NULL,
    `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RefreshToken` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `token` TEXT NOT NULL,
    `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` DATETIME(3) NULL,

    UNIQUE INDEX `RefreshToken_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Customer` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `date` DATE NULL,
    `companyName` VARCHAR(20) NULL,
    `companyAddress` TEXT NULL,
    `companyNumber` VARCHAR(20) NULL,
    `emailId` VARCHAR(100) NOT NULL,
    `registerTransferAgentName` VARCHAR(20) NULL,
    `registerTransferAgentAdress` TEXT NULL,
    `registerTransferAgentContactNumber` VARCHAR(20) NULL,
    `registerTransferAgentEmail` VARCHAR(20) NULL,
    `bonusDate` DATE NULL,
    `splitDate` DATE NULL,
    `notaryDate` DATE NULL,
    `ledgerFolio` VARCHAR(20) NULL,
    `tableSDT` TEXT NULL,
    `totalShares` TEXT NULL,
    `faceValueAsOnToday` VARCHAR(20) NULL,
    `holdShareQuantitySelf` VARCHAR(20) NULL,
    `companyHoldUndeliveredShareQuantity` VARCHAR(20) NULL,
    `holdShareQuantitySelfFaceValue` VARCHAR(20) NULL,
    `oldCompanyName` VARCHAR(20) NULL,
    `oldQuantityholdShare` VARCHAR(20) NULL,
    `ywdATabelData` TEXT NULL,
    `fhnameInPancardExactSpelling` VARCHAR(100) NULL,
    `fhrateInPercentage` VARCHAR(20) NULL,
    `fhnameAsPerShareCertificate` VARCHAR(20) NULL,
    `fhfatherOrHusbandName` VARCHAR(20) NULL,
    `fhcontactNumber` VARCHAR(20) NULL,
    `fhemail` VARCHAR(20) NULL,
    `fhpancardNumber` VARCHAR(20) NULL,
    `fhcity` VARCHAR(20) NULL,
    `fhaddressSameInAadharcard` TEXT NULL,
    `fholdAddressCompanyRegister` TEXT NULL,
    `fhpinCode` VARCHAR(20) NULL,
    `fhbusiness` VARCHAR(20) NULL,
    `fhgender` VARCHAR(20) NULL,
    `fhstate` VARCHAR(20) NULL,
    `fhage` VARCHAR(20) NULL,
    `fhaadharCardNumber` VARCHAR(20) NULL,
    `fhnameInAadharcardExactSpeling` VARCHAR(20) NULL,
    `jhnameInPancardExactSpelling` VARCHAR(100) NULL,
    `jhnameAsPerShareCertificate` VARCHAR(20) NULL,
    `jhfatherOrHusbandName` VARCHAR(20) NULL,
    `jhcontactNumber` VARCHAR(20) NULL,
    `jhpancardNumber` VARCHAR(20) NULL,
    `jhcity` VARCHAR(20) NULL,
    `jhaddressSameInAadharcard` TEXT NULL,
    `jholdAddressCompanyRegister` TEXT NULL,
    `jhgender` VARCHAR(20) NULL,
    `jhstate` VARCHAR(20) NULL,
    `jhage` VARCHAR(20) NULL,
    `jhaadharcardNumber` VARCHAR(20) NULL,
    `jhnameInAadharcardExactSpeling` VARCHAR(20) NULL,
    `fhbankName` VARCHAR(20) NULL,
    `fhbankAddress` TEXT NULL,
    `fhholderAddressInBank` TEXT NULL,
    `fhaccountTypeSavingorCurrent` VARCHAR(20) NULL,
    `fhaccountNumber` VARCHAR(20) NULL,
    `fhbankTelephoneNumber` VARCHAR(20) NULL,
    `fhbankIfscCode` VARCHAR(20) NULL,
    `fhbankEmail` VARCHAR(20) NULL,
    `fhnineDigitMICRNumber` VARCHAR(20) NULL,
    `fhnameAsPerBankAccount` VARCHAR(20) NULL,
    `jhbankName` VARCHAR(20) NULL,
    `jhbankAddress` TEXT NULL,
    `jhholderAddressInBank` TEXT NULL,
    `jhaccountTypeSavingorCurrent` VARCHAR(20) NULL,
    `jhaccountNumber` VARCHAR(20) NULL,
    `jhemail` VARCHAR(20) NULL,
    `jhbankTelephoneNumber` VARCHAR(20) NULL,
    `jhbankIfscCode` VARCHAR(20) NULL,
    `jhbankEmail` VARCHAR(20) NULL,
    `jhnineDigitMICRNumber` VARCHAR(20) NULL,
    `jhnameAsPerBankAccount` VARCHAR(20) NULL,
    `dpName` VARCHAR(20) NULL,
    `dematNumber` VARCHAR(20) NULL,
    `cdslOrNsdl` VARCHAR(20) NULL,
    `nameAsPerDematAccount` VARCHAR(20) NULL,
    `nomineeName` VARCHAR(20) NULL,
    `nomineeFatherOrHusbandName` VARCHAR(20) NULL,
    `nomineeAddress` TEXT NULL,
    `nomineeHolderRelationShip` VARCHAR(20) NULL,
    `nomineeBirthdate` DATE NULL,
    `w1NameInPancardExactSpelling` VARCHAR(20) NULL,
    `w1addressSameInAadharcard` TEXT NULL,
    `w1nameInAadharcardExactSpelling` VARCHAR(20) NULL,
    `w2nameInPancardExactSpelling` VARCHAR(20) NULL,
    `w2addressSameInAadharcard` TEXT NULL,
    `w2nameInAadharcardExactSpelling` VARCHAR(20) NULL,
    `s1nameInPancardExactSpelling` VARCHAR(20) NULL,
    `s1nameInAadharcard` VARCHAR(20) NULL,
    `s1addressAadharcard` TEXT NULL,
    `s1age` VARCHAR(20) NULL,
    `s1income` VARCHAR(20) NULL,
    `s1email` VARCHAR(20) NULL,
    `s1mobileNumber` VARCHAR(20) NULL,
    `s1itReturnShowAddress` TEXT NULL,
    `s2nameInPancardExactSpelling` VARCHAR(20) NULL,
    `s2nameInAadharcard` VARCHAR(20) NULL,
    `s2addressAadharcard` TEXT NULL,
    `s2age` VARCHAR(20) NULL,
    `s2income` VARCHAR(20) NULL,
    `s2email` VARCHAR(20) NULL,
    `s2mobileNumber` VARCHAR(20) NULL,
    `s2itReturnShowAddress` TEXT NULL,
    `policeStationName` VARCHAR(20) NULL,
    `oldName` VARCHAR(20) NULL,
    `newname` VARCHAR(20) NULL,
    `deathHolderName1` VARCHAR(20) NULL,
    `deathHolderName2` VARCHAR(20) NULL,
    `deathOfAddress` TEXT NULL,
    `certificateDeathHolderName1` VARCHAR(20) NULL,
    `certificateDeathHolderName2` VARCHAR(20) NULL,
    `legalNamePancard` VARCHAR(20) NULL,
    `successionCertificateNumberYear` VARCHAR(20) NULL,
    `successionCertificateCourtOrderDateAndYear` VARCHAR(20) NULL,
    `nameInPancardExectSpelling` VARCHAR(20) NULL,
    `nameAsPerShareCertificate` VARCHAR(20) NULL,
    `fatherOrHusbandName` VARCHAR(20) NULL,
    `contactNumber` VARCHAR(20) NULL,
    `email` VARCHAR(20) NULL,
    `pancardNumber` VARCHAR(20) NULL,
    `city` VARCHAR(20) NULL,
    `deathOfHolderFirstHolder` DATETIME(3) NULL,
    `deathOfHolderSecondHolder` DATETIME(3) NULL,
    `deathHolderFirstCity` VARCHAR(20) NULL,
    `deathHolderSecondCity` VARCHAR(20) NULL,
    `addressSameInAadharcard` TEXT NULL,
    `oldAddressCompanyRegister` TEXT NULL,
    `gender` VARCHAR(20) NULL,
    `state` VARCHAR(20) NULL,
    `age` VARCHAR(20) NULL,
    `aadharcardNumber` VARCHAR(20) NULL,
    `nameInAdharcardExactSpeling` VARCHAR(100) NULL,
    `lhabankName` VARCHAR(20) NULL,
    `lhabankAddress` TEXT NULL,
    `lhaholderAddressInBank` TEXT NULL,
    `lhaaccountTypeSavingorCurrent` VARCHAR(20) NULL,
    `lhaaccountNumber` VARCHAR(20) NULL,
    `lhabankTelephoneNumber` VARCHAR(20) NULL,
    `lhabankIfscCode` VARCHAR(20) NULL,
    `lhanineDigitMICRNumber` VARCHAR(20) NULL,
    `lhanameAsPerBankAccount` VARCHAR(20) NULL,
    `lhadpName` VARCHAR(20) NULL,
    `lhadematNumber` VARCHAR(20) NULL,
    `lhacdslOrNsdl` VARCHAR(20) NULL,
    `lhanameAsPerDematAccount` VARCHAR(20) NULL,
    `iepfDividendAmount` VARCHAR(20) NULL,
    `iepfDividendYear` VARCHAR(20) NULL,
    `referenceLetterNo` VARCHAR(20) NULL,
    `referenceLetterdate` DATETIME(3) NULL,
    `otherLegalHears` TEXT NULL,
    `currentYear` VARCHAR(10) NULL,
    `dpId` VARCHAR(10) NULL,
    `clientId` VARCHAR(10) NULL,
    `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CustomerTemplate` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `customerId` INTEGER NOT NULL,
    `templateId` INTEGER NULL,
    `templateType` VARCHAR(191) NOT NULL,
    `templateData` TEXT NULL,
    `templateTitle` VARCHAR(191) NULL,
    `order` INTEGER NULL,
    `isCustomMainContentTemplate` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Template` ADD CONSTRAINT `Template_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Customer` ADD CONSTRAINT `Customer_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CustomerTemplate` ADD CONSTRAINT `CustomerTemplate_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `Customer`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CustomerTemplate` ADD CONSTRAINT `CustomerTemplate_templateId_fkey` FOREIGN KEY (`templateId`) REFERENCES `Template`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
