export declare type CreateCustomerRepoInput = {
  //   id: number;
  userId: number;
  date: Date | null;
  companyName: string | null;
  companyAddress: string | null;
  companyNumber: string | null;
  emailId: string;
  registerTransferAgentName: string | null;
  registerTransferAgentAdress: string | null;
  registerTransferAgentContactNumber: string | null;
  registerTransferAgentEmail: string | null;
  ledgerFolio: string | null;
  shareCertificateNumber: string | null;
  distinctiveNumber: string | null;
  totalShareQuantity: string | null;
  faceValueAsOnToday: string | null;
  holdShareQuantitySelf: string | null;
  companyHoldUndeliveredShareQuantity: string | null;
  holdShareQuantitySelfFaceValue: string | null;
  oldCompanyName: string | null;
  oldQuantityholdShare: string | null;
  ywdATabelData: string | null;
  fhnameInPancardExactSpelling: string | null;
  fhrateInPercentage: string | null;
  fhnameAsPerShareCertificate: string | null;
  fhfatherOrHusbandName: string | null;
  fhcontactNumber: string | null;
  fhemail: string | null;
  fhpancardNumber: string | null;
  fhcity: string | null;
  fhaddressSameInAadharcard: string | null;
  fholdAddressCompanyRegister: string | null;
  fhpinCode: string | null;
  fhbusiness: string | null;
  fhgender: string | null;
  fhstate: string | null;
  fhage: string | null;
  fhaadharCardNumber: string | null;
  fhnameInAadharcardExactSpeling: string | null;
  jhnameInPancardExactSpelling: string | null;
  jhnameAsPerShareCertificate: string | null;
  jhfatherOrHusbandName: string | null;
  jhcontactNumber: string | null;
  jhemail: string | null;
  jhpancardNumber: string | null;
  jhcity: string | null;
  jhaddressSameInAadharcard: string | null;
  jholdAddressCompanyRegister: string | null;
  jhgender: string | null;
  jhstate: string | null;
  jhage: string | null;
  jhaadharcardNumber: string | null;
  jhnameInAadharcardExactSpeling: string | null;
  fhbankName: string | null;
  fhbankAddress: string | null;
  fhholderAddressInBank: string | null;
  fhaccountTypeSavingorCurrent: string | null;
  fhaccountNumber: string | null;
  fhbankTelephoneNumber: string | null;
  fhbankIfscCode: string | null;
  fhbankEmail: string | null;
  fhnineDigitMICRNumber: string | null;
  fhnameAsPerBankAccount: string | null;
  jhbankName: string | null;
  jhbankAddress: string | null;
  jhholderAddressInBank: string | null;
  jhaccountTypeSavingorCurrent: string | null;
  jhaccountNumber: string | null;
  jhbankTelephoneNumber: string | null;
  jhbankIfscCode: string | null;
  jhbankEmail: string | null;
  jhnineDigitMICRNumber: string | null;
  jhnameAsPerBankAccount: string | null;
  dpName: string | null;
  dematNumber: string | null;
  cdslOrNsdl: string | null;
  nameAsPerDematAccount: string | null;
  nomineeName: string | null;
  nomineeFatherOrHusbandName: string | null;
  nomineeAddress: string | null;
  nomineeHolderRelationShip: string | null;
  nomineeBirthdate: Date | null;
  //   createdAt: Date;
  //   updatedAt: Date | null;
};

export declare type CreateCustomerServiceInput = {
  //   id: number;
  userId: number;
  date: Date | null;
  companyName: string | null;
  companyAddress: string | null;
  companyNumber: string | null;
  emailId: string;
  registerTransferAgentName: string | null;
  registerTransferAgentAdress: string | null;
  registerTransferAgentContactNumber: string | null;
  registerTransferAgentEmail: string | null;
  ledgerFolio: string | null;
  shareCertificateNumber: string | null;
  distinctiveNumber: string | null;
  totalShareQuantity: string | null;
  faceValueAsOnToday: string | null;
  holdShareQuantitySelf: string | null;
  companyHoldUndeliveredShareQuantity: string | null;
  holdShareQuantitySelfFaceValue: string | null;
  oldCompanyName: string | null;
  oldQuantityholdShare: string | null;
  ywdATabelData: {
    year: string;
    warrantNo: string;
    ddMicrNo: string;
    amount: string;
  }[];
  fhnameInPancardExactSpelling: string | null;
  fhrateInPercentage: string | null;
  fhnameAsPerShareCertificate: string | null;
  fhfatherOrHusbandName: string | null;
  fhcontactNumber: string | null;
  fhemail: string | null;
  fhpancardNumber: string | null;
  fhcity: string | null;
  fhaddressSameInAadharcard: string | null;
  fholdAddressCompanyRegister: string | null;
  fhpinCode: string | null;
  fhbusiness: string | null;
  fhgender: string | null;
  fhstate: string | null;
  fhage: string | null;
  fhaadharCardNumber: string | null;
  fhnameInAadharcardExactSpeling: string | null;
  jhnameInPancardExactSpelling: string | null;
  jhnameAsPerShareCertificate: string | null;
  jhfatherOrHusbandName: string | null;
  jhcontactNumber: string | null;
  jhemail: string | null;
  jhpancardNumber: string | null;
  jhcity: string | null;
  jhaddressSameInAadharcard: string | null;
  jholdAddressCompanyRegister: string | null;
  jhgender: string | null;
  jhstate: string | null;
  jhage: string | null;
  jhaadharcardNumber: string | null;
  jhnameInAadharcardExactSpeling: string | null;
  fhbankName: string | null;
  fhbankAddress: string | null;
  fhholderAddressInBank: string | null;
  fhaccountTypeSavingorCurrent: string | null;
  fhaccountNumber: string | null;
  fhbankTelephoneNumber: string | null;
  fhbankIfscCode: string | null;
  fhbankEmail: string | null;
  fhnineDigitMICRNumber: string | null;
  fhnameAsPerBankAccount: string | null;
  jhbankName: string | null;
  jhbankAddress: string | null;
  jhholderAddressInBank: string | null;
  jhaccountTypeSavingorCurrent: string | null;
  jhaccountNumber: string | null;
  jhbankTelephoneNumber: string | null;
  jhbankIfscCode: string | null;
  jhbankEmail: string | null;
  jhnineDigitMICRNumber: string | null;
  jhnameAsPerBankAccount: string | null;
  dpName: string | null;
  dematNumber: string | null;
  cdslOrNsdl: string | null;
  nameAsPerDematAccount: string | null;
  nomineeName: string | null;
  nomineeFatherOrHusbandName: string | null;
  nomineeAddress: string | null;
  nomineeHolderRelationShip: string | null;
  nomineeBirthdate: Date | null;
  //   createdAt: Date;
  //   updatedAt: Date | null;
};
